### ISSUE TITLE
saving the copy of colab file in github is not working properly

### ISSUE THREAD

**Issue by chakramit296** [internship-kaard/zenteiq-kaard#1]
I tried to save a copy of the colab file in github reposity, it redirected to github but the resulted saved file was not as original file.
![git_page-0001](https://user-images.githubusercontent.com/115872696/234899980-7af32c98-e7bc-45df-98f8-41c289ca745d.jpg)
Above is how the copy shows in github.
Can anyone help me with it?

**Comment by KoushikEng** [comment]
checking it out ?

**Comment by KoushikEng** [comment]
**Issue resolved**
please check it out @internship-kaard/algorithm-artists @ac-infinityhub

**Comment by chakramit296** [comment]
Thank you
